package com.example.demo.entity;

public class MMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.menu_id
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.menu_type_id
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    private Integer menuTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.menu_name
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    private String menuName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.menu_id
     *
     * @return the value of m_menu.menu_id
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.menu_id
     *
     * @param menuId the value for m_menu.menu_id
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.menu_type_id
     *
     * @return the value of m_menu.menu_type_id
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    public Integer getMenuTypeId() {
        return menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.menu_type_id
     *
     * @param menuTypeId the value for m_menu.menu_type_id
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    public void setMenuTypeId(Integer menuTypeId) {
        this.menuTypeId = menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.menu_name
     *
     * @return the value of m_menu.menu_name
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.menu_name
     *
     * @param menuName the value for m_menu.menu_name
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
}