package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.MMenuType;
import com.example.demo.entity.MMenuTypeExample;
@Mapper
public interface MMenuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    long countByExample(MMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int deleteByExample(MMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int insert(MMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int insertSelective(MMenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    List<MMenuType> selectByExample(MMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int updateByExampleSelective(@Param("record") MMenuType record, @Param("example") MMenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu_type
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int updateByExample(@Param("record") MMenuType record, @Param("example") MMenuTypeExample example);
}