package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.MMenu;
import com.example.demo.entity.MMenuExample;
@Mapper
public interface MMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    long countByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int deleteByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int insert(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int insertSelective(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    List<MMenu> selectByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    MMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int updateByExampleSelective(@Param("record") MMenu record, @Param("example") MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int updateByExample(@Param("record") MMenu record, @Param("example") MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int updateByPrimaryKeySelective(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated Mon Jun 10 00:51:47 JST 2019
     */
    int updateByPrimaryKey(MMenu record);
}